server:
  port: 8082
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///pethome?useSSL=true
    username: root
    password: 123456
mybatis:
  type-aliases-package: cn.lngex.org.domain,cn.lngex.org.query,
logging:
  level:
    cn:
      lngex: trace